configs:
- id: zone-multiproject
  config:
    name: mzone-1-multiproject-1
    parameters:
      meId: HOST_GROUP-1234567890123456
      webAppTaggingName:
        api: auto-tag
        config: application-tagging-multiproject
        project: cinema-infrastructure
        property: name
        type: reference
    template: zone.json
    skip: false
  groupOverrides:
  - group: development
    override:
      parameters:
        environment: environment1
  - group: production
    override:
      parameters:
        environment: environment2
